#!/usr/bin/env bash

main() {
  export LD_PRELOAD="@gtk4LayerShell@/lib/libgtk4-layer-shell.so${LD_PRELOAD:+:$LD_PRELOAD}"
  exec "@python@" "@script@" "$@"
}

main "$@"

# vim: set ft=sh et ts=2 sw=2 :
