{
  imports = [
    ./browser.nix
    ./browser-daemon.nix
    ./cli-proxy-api.nix
    ./dotfiles.nix
    ./domains.nix
    ./falcon-sensor-vm.nix
    ./hardware.nix
    ./hermes.nix
    ./ktunnel.nix
    ./main-user.nix
    ./monit-checks.nix
    ./nginx-vhost.nix
    ./nix-host-overrides.nix
    ./nixos-config-symlink.nix
    ./options
    ./sops.nix
    ./stalwart.nix
    ./syncthing
    ./theme.nix
  ];
}
