{
  lib,
  config,
  pkgs,
  ...
}:
let
  cfg = config.services.ppd-react;

  profileVariable =
    profile: "TDP_PROFILE_${lib.toUpper (lib.replaceStrings [ "-" ] [ "_" ] profile)}";

  profileLimits =
    profile:
    lib.concatStringsSep " " (
      map toString [
        profile.stapmLimit
        profile.fastLimit
        profile.slowLimit
        profile.apuSlowLimit
      ]
    );

  ppdReactConfig = pkgs.writeText "ppd-react.conf" (
    lib.concatStringsSep "\n" (
      [
        "# Generated by NixOS; configure services.ppd-react in Nix instead."
      ]
      ++ lib.optional (
        cfg.tdp.enable && cfg.tdp.command != null
      ) "TDP_COMMAND=${lib.escapeShellArg (toString cfg.tdp.command)}"
      ++ lib.mapAttrsToList (
        name: profile: "${profileVariable name}=${lib.escapeShellArg (profileLimits profile)}"
      ) cfg.tdp.profiles
    )
    + "\n"
  );

  ppdReact = pkgs.writeShellApplication {
    name = "ppd-react";
    runtimeInputs = with pkgs; [
      gawk
      jq
      libnotify
      systemd
      util-linux
    ];
    text = builtins.readFile ./ppd-react.sh;
  };
in
{
  options.services.ppd-react = {
    enable = lib.mkEnableOption "power-profiles-daemon integration service" // {
      default = true;
    };

    tdp = {
      enable = lib.mkEnableOption "TDP changes in response to power profiles";

      command = lib.mkOption {
        type = lib.types.nullOr lib.types.path;
        default = null;
        description = "Command accepting ryzenadj-style TDP limit arguments.";
      };

      profiles = lib.mkOption {
        type = lib.types.attrsOf (
          lib.types.submodule {
            options = {
              stapmLimit = lib.mkOption {
                type = lib.types.ints.between 1000 1000000;
                description = "STAPM limit in milliwatts.";
              };
              fastLimit = lib.mkOption {
                type = lib.types.ints.between 1000 1000000;
                description = "Fast PPT limit in milliwatts.";
              };
              slowLimit = lib.mkOption {
                type = lib.types.ints.between 1000 1000000;
                description = "Slow PPT limit in milliwatts.";
              };
              apuSlowLimit = lib.mkOption {
                type = lib.types.ints.between 1000 1000000;
                description = "APU slow PPT limit in milliwatts.";
              };
            };
          }
        );
        default = { };
        description = "TDP limits keyed by power-profiles-daemon profile name.";
      };
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = !cfg.tdp.enable || cfg.tdp.command != null;
        message = "services.ppd-react.tdp.command must be set when TDP integration is enabled";
      }
    ];

    # power-profiles-daemon conflicts with tlp
    # https://linrunner.de/tlp/faq/ppd.html
    services = {
      power-profiles-daemon.enable = lib.mkForce true;
      tlp.enable = lib.mkForce false;
    };

    systemd.services.ppd-react = {
      description = "React to power-profiles-daemon profile changes";
      wantedBy = [ "multi-user.target" ];
      after = [
        "dbus.service"
        "power-profiles-daemon.service"
      ];
      wants = [ "power-profiles-daemon.service" ];
      serviceConfig = {
        ExecStart = "${ppdReact}/bin/ppd-react --config=${ppdReactConfig}";
        Restart = "always";
        RestartSec = "1s";
      };
    };
  };
}
