---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: xmrig
  namespace: xmr
  labels:
    app: xmrig
spec:
  selector:
    matchLabels:
      app: xmrig
  template:
    metadata:
      labels:
        app: xmrig
    spec:
      nodeSelector:
        node-role.kubernetes.io/compute: "true"
      containers:
        - name: xmrig
          image: artifactory.prod.capp.wiit-cloud.io/docker-ghcr-io-remote/metal3d/xmrig:latest
          command:
            - /bin/bash
            - -c
            - |
              node_name="${NODE_NAME:-${HOSTNAME:-$(hostname)}}"
              exec xmrig -o "${POOL_URL}" --nicehash -p "${POOL_PASS}" --rig-id "${node_name}" --donate-level 1
          securityContext:
            privileged: true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POOL_URL
              value: xmrig-proxy.xmr.svc.cluster.local:3333
            - name: POOL_PASS
              valueFrom:
                secretKeyRef:
                  name: xmrig-proxy-password
                  key: password
