# shellcheck shell=bash
# Concatenated after lib.sh; see lib.sh for why this has no shebang.

prepare_final_cutover() {
  # All source writers must stop before *any* final dataset is copied.
  [[ "$TARGET" == all ]] || die "Final cutover requires target all so media and VM data are quiesced together"
  if [[ $DRY_RUN -eq 1 ]]
  then
    log "[DRY-RUN] Would inhibit presync, stop HA and source containers, then copy all datasets"
    return 0
  fi
  ssh "${SSH_OPTS[@]}" "${DEST_HOST}" \
    "touch /var/lib/fnuc-migration/cutover && sudo -n systemctl stop 'fnuc-migration-presync-*.timer'"
  [[ "$(source_vm_disk)" == /var/lib/libvirt/images/haos-11.2-restored.qcow2 ]] || die "Resolve source snapshot chain before cutover"
  [[ "$(source_vm_disk --inactive)" == /var/lib/libvirt/images/haos-11.2-restored.qcow2 ]] || die "Resolve persistent source snapshot chain before cutover"
  local vm_state remaining=120
  vm_state=$(source_virsh domstate home-assistant)
  case "$vm_state" in
    running) source_virsh shutdown home-assistant ;;
    "shut off") ;;
    *) die "Unsafe source VM state for final cutover: ${vm_state}" ;;
  esac
  while [[ "$(source_virsh domstate home-assistant)" != "shut off" ]]
  do
    [[ $remaining -gt 0 ]] || die "HA did not stop; refusing final copies"
    sleep 2
    remaining=$((remaining - 2))
  done
  ssh "${SSH_OPTS[@]}" "${SOURCE_HOST}" 'sudo -n bash -se' <<'REMOTE'
containers=$(docker ps -q)
if [[ -n "$containers" ]]
then
  # Docker IDs are generated by Docker and contain no whitespace.
  docker stop $containers
fi
[[ -z "$(docker ps -q)" ]]
REMOTE
  warn "Source HA and containers are stopped for cutover. They remain stopped if a later copy fails."
}

migrate_ha_vm() (
  log "=========================================================="
  log "Migrating Home Assistant OS VM (Mode: ${MODE})"
  log "=========================================================="

  local vm_img="/var/lib/libvirt/images/haos-11.2-restored.qcow2"
  local vm_nvram="/var/lib/libvirt/qemu/nvram/home-assistant_VARS.fd"
  local overlay_img="/var/lib/libvirt/images/haos-presync-overlay.qcow2"
  local source_xml="/var/lib/fnuc-migration/home-assistant-source.xml"
  local snapshot_attempted=""
  local vm_status=0
  local dest_state

  # Neither a failed status query nor paused/crashed guests permit a direct copy.
  dest_state=$(ssh "${SSH_OPTS[@]}" "${DEST_HOST}" "sudo -n env LC_ALL=C virsh -c qemu:///system domstate home-assistant")
  [[ "$dest_state" == "shut off" ]] || die "Destination HA VM must be shut off before copying"
  [[ "$(source_vm_disk)" == "$vm_img" ]] || die "Unexpected source disk/overlay; resolve the backing chain before copying"
  [[ "$(source_vm_disk --inactive)" == "$vm_img" ]] || die "Persistent source domain does not reference the expected base disk"

  snapshot_failure() {
    if [[ -n "$snapshot_attempted" ]]
    then
      err "Snapshot operation incomplete on ${SOURCE_HOST}. Preserve ${overlay_img}; it may contain live guest writes."
      err "Inspect live/inactive domblklist and block jobs before recovery. Do not remove the overlay or copy the base as a final disk."
    fi
  }
  trap 'vm_status=$?; snapshot_failure; exit "$vm_status"' EXIT
  trap 'exit 130' INT
  trap 'exit 143' TERM

  # Ensure destination directories exist
  if [[ $DRY_RUN -eq 0 ]]
  then
    ssh "${SSH_OPTS[@]}" "${DEST_HOST}" "sudo -n mkdir -p /var/lib/libvirt/images /var/lib/libvirt/qemu/nvram"
  fi

  if [[ "$MODE" == "presync" ]]; then
    log "Presync mode: performing non-disruptive live external snapshot to pre-sync base QCOW2..."
    log "Dumping domain XML from ${SOURCE_HOST} for reference..."
    if [[ $DRY_RUN -eq 0 ]]; then
      ssh "${SSH_OPTS[@]}" "${DEST_HOST}" "sudo -n mkdir -p /var/lib/fnuc-migration"
      # shellcheck disable=SC2029
      source_virsh dumpxml home-assistant | ssh "${SSH_OPTS[@]}" "${DEST_HOST}" "sudo -n tee ${source_xml} >/dev/null"
    fi

    local vm_state
    vm_state=$(source_virsh domstate home-assistant)
    log "Current VM state on ${SOURCE_HOST}: ${vm_state}"

    if [[ "$vm_state" == "running" ]]; then
      local snap_name="presync-snapshot"

      log "Creating live disk-only snapshot overlay on ${SOURCE_HOST}..."
      if [[ $DRY_RUN -eq 0 ]]; then
        snapshot_attempted=1
        source_virsh snapshot-create-as home-assistant "${snap_name}" --disk-only --atomic --diskspec "vda,file=${overlay_img}" --no-metadata
        [[ "$(source_vm_disk)" == "$overlay_img" ]] || die "Snapshot did not switch the live source disk to the expected overlay"

        log "Transferring base QCOW2 disk image to ${DEST_HOST} (sparse, inplace)..."
        run_src_rsync "${vm_img}" "${vm_img}" "--sparse" "--inplace"

        log "Transferring NVRAM..."
        run_src_rsync "${vm_nvram}" "${vm_nvram}"

        log "Committing live snapshot overlay back into base disk on ${SOURCE_HOST}..."
        source_virsh blockcommit home-assistant vda --base "$vm_img" --top "$overlay_img" --active --pivot --shallow --verbose
        [[ "$(source_vm_disk)" == "$vm_img" ]] || die "Live source disk did not pivot back to the base; preserving overlay"
        [[ "$(source_vm_disk --inactive)" == "$vm_img" ]] || die "Persistent source domain still references an overlay; preserving it"
        # shellcheck disable=SC2029
        ssh "${SSH_OPTS[@]}" "${SOURCE_HOST}" "sudo -n rm -- ${overlay_img}"
        snapshot_attempted=""
      else
        log "[DRY-RUN] Would create snapshot overlay ${overlay_img}, rsync base image to ${DEST_HOST}, and blockcommit back to base"
      fi
    elif [[ "$vm_state" == "shut off" ]]
    then
      log "VM is not running on ${SOURCE_HOST} (${vm_state}); syncing QCOW2 directly..."
      run_src_rsync "${vm_nvram}" "${vm_nvram}"
      run_src_rsync "${vm_img}" "${vm_img}" "--sparse" "--inplace"
    else
      die "Refusing to copy disk from source VM state: ${vm_state}"
    fi

    log "HA VM pre-sync step completed successfully without disrupting running VM."
    return 0
  fi

  # From here on, MODE is "final"
  if [[ $DRY_RUN -eq 0 ]]; then
    log "Final mode: gracefully shutting down home-assistant VM on ${SOURCE_HOST}..."
    if [[ "$(source_virsh domstate home-assistant)" != "shut off" ]]
    then
      source_virsh shutdown home-assistant
    fi

    log "Waiting for VM to stop..."
    local timeout=60
    local vm_stopped=0
    while [[ $timeout -gt 0 ]]; do
      local state
      state=$(source_virsh domstate home-assistant)
      if [[ "$state" =~ "shut off" ]]; then
        log "VM successfully shut off."
        vm_stopped=1
        break
      fi
      sleep 2
      timeout=$((timeout - 2))
    done

    if [[ $vm_stopped -eq 0 ]]; then
      die "CRITICAL: VM did not shut off cleanly in 60s on ${SOURCE_HOST}! Refusing to copy live disk. Please stop the VM manually and re-run."
    fi

    # Disable pre-sync timer on destination host now that cutoff is reached
    log "Cutoff reached: disabling fnuc-migration-presync-*.timer on ${DEST_HOST}..."
    ssh "${SSH_OPTS[@]}" "${DEST_HOST}" "sudo -n systemctl stop 'fnuc-migration-presync-*.timer'"
  else
    log "[DRY-RUN] Would shut down home-assistant VM on ${SOURCE_HOST} and disable presync timer on ${DEST_HOST}"
  fi

  # 1. Dump libvirt domain XML for reference
  log "Dumping domain XML from ${SOURCE_HOST}..."
  if [[ $DRY_RUN -eq 0 ]]; then
    ssh "${SSH_OPTS[@]}" "${DEST_HOST}" "sudo -n mkdir -p /var/lib/fnuc-migration"
    # shellcheck disable=SC2029
    source_virsh dumpxml home-assistant | ssh "${SSH_OPTS[@]}" "${DEST_HOST}" "sudo -n tee ${source_xml} >/dev/null"
  fi

  # 2. Transfer NVRAM from powered-off VM
  log "Transferring NVRAM from powered-off VM..."
  run_src_rsync "${vm_nvram}" "${vm_nvram}"

  # 3. Transfer QCOW2 disk image from powered-off VM
  log "Transferring QCOW2 disk image from powered-off VM (sparse)..."
  run_src_rsync "${vm_img}" "${vm_img}" "--sparse" "--inplace"

  log "Home Assistant VM migration step (${MODE}) completed successfully."
)

# vim: set ft=sh et ts=2 sw=2 :
