name: Terraform Format Check

on:
  push:
    paths:
      - 'terraform/**.tf'
  pull_request:
    paths:
      - 'terraform/**.tf'

jobs:
  fmt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.5.7'

    - name: Check Terraform files
      run: terraform fmt -check -recursive
      working-directory: ./terraform

