{
  lib,
  config,
  pkgs,
  ...
}:
let
  cfg = config.services.ppd-react;

  profileVariable =
    profile: "TDP_PROFILE_${lib.toUpper (lib.replaceStrings [ "-" ] [ "_" ] profile)}";

  profileLimits =
    profile:
    lib.concatStringsSep " " (
      map toString [
        profile.stapmLimit
        profile.fastLimit
        profile.slowLimit
        profile.apuSlowLimit
      ]
    );

  ppdReactConfig = pkgs.writeText "ppd-react.conf" (
    lib.concatStringsSep "\n" (
      [
        "# Generated by NixOS; configure services.ppd-react in Nix instead."
      ]
      ++ lib.optional (
        cfg.tdp.enable && cfg.tdp.command != null
      ) "TDP_COMMAND=${lib.escapeShellArg (toString cfg.tdp.command)}"
      ++ lib.mapAttrsToList (
        name: profile: "${profileVariable name}=${lib.escapeShellArg (profileLimits profile)}"
      ) cfg.tdp.profiles
    )
    + "\n"
  );

  ppdReact = pkgs.writeShellApplication {
    name = "ppd-react";
    runtimeInputs = with pkgs; [
      gawk
      jq
      libnotify
      systemd
      util-linux
    ];
    text = builtins.readFile ./ppd-react.sh;
  };
in
{
  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = !cfg.tdp.enable || cfg.tdp.command != null;
        message = "services.ppd-react.tdp.command must be set when TDP integration is enabled";
      }
    ];

    # power-profiles-daemon conflicts with tlp
    # https://linrunner.de/tlp/faq/ppd.html
    services = {
      power-profiles-daemon.enable = lib.mkForce true;
      tlp.enable = lib.mkForce false;
    };

    systemd.services.ppd-react = {
      description = "React to power-profiles-daemon profile changes";
      # Start as part of power-profiles-daemon, after it has initialized its
      # current profile. This avoids the multi-user ordering cycle and makes
      # the initial TDP apply happen before user-session widgets read it.
      wantedBy = [ "power-profiles-daemon.service" ];
      after = [
        "dbus.service"
        "power-profiles-daemon.service"
      ];
      serviceConfig = {
        ExecStart = "${ppdReact}/bin/ppd-react --config=${ppdReactConfig}";
        Restart = "always";
        RestartSec = "1s";
      };
    };
  };
}
